# avoid double builds on pull requests
branches:
  only:
    master

jobs:
  include:
    # Update JSON
    - stage: Update JSON
      addons:
        apt:
          packages: python-beautifulsoup
      script:
        # push updates only for master (PR changes must be committed to master before they are taken into account)
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./push_updates.sh; fi

env:
  global:
    # to create secure for travis-ci.com
    # 1. create personal access token with public_repo permissions
    # 2. clone this repo (not a fork)
    # 3. run in the clone: travis encrypt GH_TOKEN="<access_token>" --pro (GH_TOKEN is the variable which is used in push_updates.sh)
    # 4. set output below
    - secure: "a0w5jZaG0hWNG4oiMhlEoi0oIktz3OUyozkGpSAeK5HDVtcy8zKNpt1GVYLdkXWXhTxwpnWGnVEcisrT5xkbweIJth7fxPEjA4EqCVDhUhoqZ5dtHgbAEmGjWxI9YO2x2cfOyyHRXPsJJQK2LFkI9uA8oJpdZ/aNM3BaR0IHVqK5xcK24LlaoN9bBlAYslyVphlWPW20ifjsxNC2ZL4OmF0p8tlYkCgPWSZpwpFpQmojPA/NurGP1OvRZeFXub3FKXOohZZNlaxMhc5aFs2bQtBZlr+h4RPZPVXujFiWLfOwys6GCtLzyKt2z8+FS8iE2rF+BvEr30CQgXD/mPIx6RXIdx5ZPMReO+ixAyONslB8nOwwsTaFtDK0W/n/HSH+mC4YArBTfziF6UBo1K5lMxuipgGRbG35bnGjKshKRWU8jSABvYQNRWJjDBCKRjUKCbGLcmXU/Do4+MXsp6i5j8qwekGw5eHPPtePGRw10kvDz9S03cWEJGs/DVNbCP5ft/ADdXD9ccSATa7KI7GwQNQdDya50Pwk7+XV6It62gFxWrFIkIXT6I0HVtz69r0a/J7n/i56H8qR/Rx193srbicrbEs1iPKzsAHqdVaFH5OiMzH4XoZCJd+zL5ueXGyacMvO7a4hFh2yMaqKqGXM8T7aVjX7tOqO9oS0LZ6QF6U="
