# avoid double builds on pull requests
branches:
  only:
    master

jobs:
  include:
    # Update JSON
    - stage: Update JSON
      language: python
      install: pip install requests beautifulsoup4 html5lib
      script:
        # push updates only for master (PR changes must be committed to master before they are taken into account)
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./push_updates.sh; fi
      env:
        # to create secure for travis-ci.com
        # 1. create personal access token with public_repo permissions
        # 2. clone this repo (not a fork)
        # 3. run in the clone: travis encrypt GH_TOKEN="<access_token>" --pro (GH_TOKEN is the variable which is used in push_updates.sh)
        # 4. set output below
        - secure: "cdGVQUiXETZuO9gKdM8Picu3A15czXSCiGrHO9Xkl/k/8lzGMBfLHdNXJs4vMwxLj9nshmPnVnvVhgNsGM2dTi4zZzyS1iRCDuqWtcDWPLbxEI7aZXGvdCvwiblD/x9RiE8XRW+36QVEhKhWgVZrvjfn9joAcLP7SNa5uj8uANc2j9sMx9eVUlP4/vwQWA7q3JoeyCcoeni+Gg+I+pQ+MqbwpVrjp9iCRcdE4dlFEyBeZBqzhW6TD0kLpVgp15zrOBAoXyv/DEm5LwQ8Vc65nDAOoL7jdKj4YwhXKX3zTfZ+WtFPmC6otOmJLSS2TXZYRrt0zJYG/TfcmGg/DLNwOaGg+RprSPplybCKJk3Eyw7dkNUo9U1XBfMdJUz3RFBm2rGd+jkTr36Jd4DBFrgiL4njZWuvx7dN2ybvlyZlytCWYRFCoZn7zBX5dwwFEoZoyVvcE5NNlqMNJg4jwtcNdK6PVhmfKk6k4Z+MrC4ikqDRlqK+SL3NOUt3JbJpazESGEeh0nvOhXZiA2RiY0/3fi7m9UByLjOvTY5X2Mz9CtB2FEjtWT3l4zZDY09CLTy2O5GDXpiYPZQsO/evfibbeuJPAqGfKnezwoXxKGsk9ZwDqjiHJ6lEmqz4wA9rUpZs61g4m+KuDwUGZsY2/ouABrEvgEtdXirN1keo9eDCBws="
