# avoid double builds on pull requests
branches:
  only:
    master

jobs:
  include:
    # Update JSON
    - stage: Update JSON
      language: python
      install: pip install requests beautifulsoup4
      script:
        # push updates only for master (PR changes must be committed to master before they are taken into account)
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./push_updates.sh; fi

env:
  global:
    # to create secure for travis-ci.com
    # 1. create personal access token with public_repo permissions
    # 2. clone this repo (not a fork)
    # 3. run in the clone: travis encrypt GH_TOKEN="<access_token>" --pro (GH_TOKEN is the variable which is used in push_updates.sh)
    # 4. set output below
    - secure: "fH9jtV/SCTMEVG4bO6dom+eXxSviH68wXDHnl9hgsHGSq6nD7n1aRFyRNsOUwKrr+A0FBPZYDUXoAj1R/wxNO71y+Xd0DDV7AxapNLMs6ZgqtJluJXZxYmB262jUJpRkaAtHX4zjsaA2oQU/TrOd97G85jfv4DyhoAdHDlQ5mtYFtmpa2PmmRcODorVnH3MoXjwwGPP0HXiKGtD5cOooQ00fLH3Vr9rRRv3sed+y8YMmT+KWeRyklUaD+a0SrOpLFiypaoXsgGNH3+OekOLK0p3US+EdU13PdhXwXEcyhCC26pkMkerxEjjSTTHMR7PijofxEBC/iXVoH2Ajwf1u2rkgkATeCX2l8p35B5QIr6ujpfQSnEM/fBFAAbZEQN90KK9O8bTcwLV+V/k8vf2hpdl6jN7cGW+7sTaTEucBfSs/oCpq9XM2v2IdhPFKfYtVRHHBTytFIKV6MyYWuQjE3IpSPsibOzA5tWUsEQ8Jt5wXS7eJnz312ZmODINk8cb7gS1k0vU1onFXphnBbWM3h6nDuF9c+urSxVCYaNAK40W6p05QtCDb6wG0brpFQZKCCO2zZueULmDXf3MK/j3HVBWmnmFUE3ZO0D6LjnWSMNJ9TCjw4jJGbZeI3qTMf5zRKM1YbA2ZX3B3qMi3HWF5LDamVaWpySg6I2l61Ylv15Q="
